services:
  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: learn_rabbitmq

    ports:
      - 25672:25672
      - 15672:15672
      - 5672:5672

    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

    restart: always

volumes:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local